version: "3.8"

services:
  # 1. LA BASE DE DATOS (MySQL)
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      -  persistent:/var/lib/
      # Si tienes un archivo .sql en una carpeta llamada 'dump', se cargará solo
      - ./dump:/docker-entrypoint-initdb.d:ro 

  # 2. EL PANEL PARA VER LA BASE DE DATOS (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      UPLOAD_LIMIT: ${PHP_UPLOAD_MAX_FILESIZE}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db

  # 3. TU BACKEND (Node.js)
  www-node-express:
    build: .
    ports:
      - "${EXPRESS_PORT}:3000"
    environment:
      - NODE_ENV=production
      # Aquí le decimos a tu código cómo conectar con la DB
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=test
      - DB_NAME=dbname
    depends_on:
      - db

volumes:
  persistent: